= Swarm

> Docker Swarm forms a multi-host ingress network overlay that connects containers running on all cluster nodes.
More inter-container networks can be configured manually.
Connections between nodes are also automatically secured through TLS authentication with certificates.

> Kubernetes allows us to define resource defaults and limitations that are applied to containers that
do not specify resources. It allows us to specify resource quotas that prevent accidental or malicious
over-usage of resources. The two combined with Namespaces provide very powerful safeguards.
They give us some of the means with which we can design the system that is truly fault tolerant by
preventing rogue containers, uncontrolled scaling, and human errors from bringing our clusters to
a grinding halt. Don’t think, even for a second, that quotas are the only thing required for building
a robust system. It isn’t the only piece of the puzzle, but it is a significant one never the less.
Namespaces combined with quotas are important. I’d even say that they are crucial. Without them,
we would be forced to create a cluster for every group, team, or a department in our organizations.
Or, we might have to resort to further tightening of the processes that prevent our teams from
exploiting the benefits behind container orchestrators.
