= POSTGRES TECHNICAL NOTE
Pierre Radermecker
2013

== Postgres enterprise

Notes:
PEM : Postgres Enterprise Manager

PPAS: Postgres Plus Advanced Server


== Servers

CIRB PROD: 192.168.14.41


== Architecture


One process per user, NO THREAD !
Processes are managed by Postmaster that acts as a listener for new connection and as a supervisor to restart them.

The term "buffer" is usually used for blocks in memory.

7500 concurrent user -> connection pooling 

16MB


== CLUSTER


A cluster is a collection of databases. Clusters have separate:
	* data directory
	* TCP port
	* set of processes

To create a cluster execute the following comming with the postgres user (! not root !):
	[postgres]$ initdb --locale en_US.UTF-8 -E UTF8 -D '/var/lib/postgres/data'

To create a second cluster on the same machine you need to:
	* as root, create a DATA directory
	* as root, change owner of the DATA directory to enterprisedb or postgres (depending on the version of postgres enterprise or community)
	* as postgres (or enterprisedb), do:
		initdb  -D '/var/lib/postgres/data'

There is a little tricky behavior with the second cluster when you want to connect with a client. By default, connections will be refused for user "enterprisedb" ... You need to change the pg_hba file and set "trust" for enterprisedb ... Then set a password with the client and put it pack to md5.

host    all             enterprisedb    192.168.104.0/24        trust


== WAL

Write Ahead Log

At all times, PostgreSQL maintains a WAL in the pg_xlog/ subdirectory of the cluster's data directory. The log describes every change made to the database's data files. This log exists primarily for crash-safety purposes: if the system crashes, the database can be restored to consistency by "replaying" the log entries made since the last checkpoint. However, the existence of the log makes it possible to use a third strategy for backing up databases: we can combine a file-system-level backup with backup of the WAL files. If recovery is needed, we restore the backup and then replay from the backed-up WAL files to bring the backup up to current time.


== EXERCICES

COPY edbstore.categories TO '/tmp/test.csv' WITH (FORMAT 'csv');


select tablename from pg_tables where tableowner='edbstore';

for t in $(pqsl -U enterprisedb -d edbstore -t
-c "select tablename from pg_tables where tableowner='edbstore'"); do pg_dump
-t edbstore.$t -U enterprisedb edbstore > $t.sql;done



select table_name from information_schema.tables where table_schema='edbstore';


== Backup & Recovery


* for small DB, we can use a sql dump several time a day:
pg_dump dbname | gzip > filename.gz
pg_dump dbname | split -b 1m - filename

=== Restore

psql dbname < infile


One of the problem with DRP is the human factor. This is not so much a problem with a database such as datomic.


== Migration

Use pgdump to migrate from postgres to postgres.


== Replication

* Hot Streaming Replication (Warm Streaming Replication or Log WAL Shipping is deprecated)
	There is a daemon process started by the PostMaster

We don't have to start the slave before the master. The slave can just wait for a master to start up.

First shutdown the master and set it up for replication by:
	1) change postgres.conf
wal_level = hot_standby
max_wal_senders = 2
wal_keep_segments = 32
archive_mode = on
archive_command = 'cp %p /data/archive/%f'
	2) change pg_hba.conf
host  replication  all 127.0.0.1/32  trust

Then take a brand new backup of the master db and ship it to the master. Locally it is just
Start the server !!
pg_basebackup -h localhost -D /opt/PostgresPlus/9.3AS/data1
( or just copy the directory if the server is down)


	PAX process


	Select * from pg_stat_activity
	select * from pg
	
== Shell utils practices

```
psql -h 192.168.14.62 -W -U pradermecker postgres < create_PGPUPPETDB.sql

export PGPASSWORD=dbpasswordforpuppetdb
ssh puppetmaster-prod 'sudo -u postgres pg_dump puppetdb ' | psql -h 192.168.14.62 -U puppetdb -w PGPUPPETDB
```