= Linux

== Script

```
#!/bin/bash -xe
while read host
do
       cat plone_team.pub | ssh alhazen@"$host".prd.srv.cirb.lan "grep plone ~/.ssh/authorized_keys || cat >> ~/.ssh/authorized_keys"
done < plone-prod-uniq.txt
```

```
pandoc --latex-engine=xelatex -o blog.pdf http://blog.jakubarnold.cz/2014/07/22/building-monad-transformers-part-1.html
```

== LVM

- change disk size on the VCloud
- create a new partition with fdisk (ie: sdb1) so we don't change anything on the existing partition table
- add this new partition as a new physical volume: `pvcreate /dev/sdb1`
- `vgextend system_vg /dev/sdb1`
- `lvextend -L+12G /dev/system_vg/data`
- `xfs_growfs /dev/system_vg/data`

or by adding a new disk using puppet :

- add a new disk on the VCloud
- after a few delay, VCloud will automatically create a new partition for instance '/dev/sdd'
- add this new partition as a new physical volume: `pvcreate /dev/sdd`. You can see it with `pvs`
- `vgextend vg_rhel /dev/sdd` (the name to 'vg_rhel' is fixed for our new RHEL 7 template)
- `puppet agent -t` will now create a new lv `nix`. You can see it with `lvs`


## Tips

Add route in windows::
+
```
route ADD 192.168.30.0 MASK 255.255.255.0 10.255.10.4
```

SCP copy from local to remote::
+
```
scp -i ~/.ssh/user_rsa -r folder user@svifscapl003.prd.srv.cirb.lan:/tmp
```

SCP copy from remote to remote::
Using your local computer
+
```
ssh-add ~/.ssh/alhazen_rsa
# Give alhazen the permission to write on targetfqdn:/srv/tmp
ssh -A -i  ~/.ssh/alhazen_rsa alhazen@sourcefqdn \
"scp -o StrictHostKeyChecking=No /srv/data/pgserver.dump alhazen@targetfqdn:/srv/tmp"

```

## Definitions

Push (SSE) vs Pull (REQ/REP)::

Application layer:: HTTP, SNMP, AMQP, XMPP, IRC, DHCP, WebDAV, SSH, FTP, SIP, Telnet

Transport layer:: TCP, UDP (SCTP)
