= Docker
Technical Notes

== Intro

A Docker environment is made up of filesystems layered over each other. At the base is a boot filesystem, docker's next layer is the root filesystem, rootfs. Then Docker takes advantage of a union mount to add more readonly filesystems on top. These filesystems are called "images". Finally, Docker mounts a read-write filesystem on top of any layers below. This is where whatever process we want our Docker container to run will execute.

User images are named using "initial/name:tag"

The `RUN` instruction in a `Dockerfile` executes commands on the current image and commits the results.



== Useful command

```
docker build -t initial/name .
docker commit containerid imagename
docker ps
docker images
docker run -i -t initial/name /bin/bash (-d for detach)

```

== Link

Links is used to enable secure communication between two containers. The first container is oddly enough called the child. This is odd because it is usually a server and it has to be started first ... The first container will expose a port and be labelled with a name.

```
# Child or first container
sudo docker run -i -t -h puppet -name puppetmaster pra/pmaster /bin/bash

# Parent or second container have all info to connect to the first
sudo docker run -i -t -h minion -name minion -link puppetmaster:puppet pra/minion /bin/bash

``` 

== SSH-tunnel

```
ssh -q -M -S my-ctrl-socket -fnNT -L 27017:localhost:27017 alhazen@pulp.irisnet.be

# to use the host network: --net host
docker run --net host -e PULP_LOGIN=$(PULP_LOGIN) -e PULP_PWD=$(PULP_PWD) --rm -v $(PWD):/code -ti test /code/bin/clean.py $(ENV) --repo-name=$(REPO_ID)

ssh -q -S my-ctrl-socket -O exit alhazen@pulp.irisnet.be 2> /dev/null
```

== Export/Import

Export acts on containers ! It currently does not work from containers to images ... It is really briddle right now (just wait for 1.0)

In the meanwhile it is possible to use any image as your base image  in the Dockfile ...

== Mount

You cannot mount a host dir with the VOLUME instruction inside the Dockerfile. You need to pass it at runtime :

```
# !! first -v, then -t !!
run -i -v /media/puppet-stack-middleware:/etc/puppet/environments/middleware_local:ro -t pra/puppetmaster /bin/bash

docker run -i -t pra/puppetmaster -v /media/puppet-stack-middleware:/etc/puppet/environments/middleware_local:ro /bin/bash
```

== Initial Win7 host setup

Win7 hosts a docker ubuntu VM (standard install) using vagrant.

Change the Vagrantfile to mount the shared `puppet-stack-middleware`directory:

    config.vm.share_folder "puppet-stack-middleware", "/media/puppet-stack-middleware", "C:/Users/pradermecker/VirtualBox VMs/shared/puppet-stack-middleware"

Connection to the docker vms from an arch vms with:

`ssh -p 2222 vagrant@10.0.2.2`

Create a dir `puppetmaster` and a file inside called `Dockerfile`. Build with `sudo docker build .`

Then you need to ssh-copy-id your public id_rsa.pub key to be able to fetch the Docker configuration from Github.

== Trouble Shouting

WARNING::
In centos `6.4` `usePAM` needs to be set to `no` while it needs to be set to `yes` in `6.5`

WARNING::
The Centos latest official images, currently 6.5, comes with a broken `centos.plus` version of `libselinux`. To remove it you need to:
```
yum downgrade --skip-broken libselinux libselinux-utils
```