= Spacemacs Cheatsheet
Pierre Radermecker <pierrer@pi3r.be>
2015

=== Magit

:===
<SPC> g e     :       Ediff a file (awesome)
<SPC> g d r   :       Revert hunk
:===

=== Helm

:===
c-k :                 "abort" helm completion !!
:===

=== Ido

:===
c-Return :            dired
c-o      :            | open in a new buffer
c-s      :            - open in a new buffer
:===

=== Search

:===
<SPC> s l   :        helm-semantic-or-imenu
<SPC> s w g :        search with google
<SPC> s f   :        search within a path
<SPC> s s   :        helm-swoop
:===

=== Misc

:===
<SPC> a u   :        "undo-tree-visualize"
<SPC> p f   :        helm-find file for your project !amazing!
<SPC> f e h :        open helm spacemacs for help
<SPC> f S   :        save all buffers
<SPC> f y   :        show file name
<SPC> i K   :        insert empty line above
<SPC> b b   :        helm find buffer
<SPC> x J / SPC x K : move lines up and down i
<SPC> r y   :        kill ring

,gg :                 jump to def (awesome!)

<SPC> p y   :  	      find tags
<SPC> /     :         ag search     
<SPC> m c R :         reload .spacemacs
<SPC> f e d :         open .spacemacs

<SPC> n r   :         narrow region
:===

(define-key evil-normal-state-map (kbd "C-p C-b") 'ibuffer)

== Surround

Enter visual state with `v`>> `e` for selecting expression >> `s` for surrounding >> `)` with parents without extra spaces.

=== Tramp
/ssh:saltmaster_testing|sudo:root@saltmaster:/srv/myfile.sls

== Replace on multiple files
